package uk.gov.justice.digital.hmpps.singleaccommodationserviceapi.query.eligibility.graph

/**
 * # Eligibility rules graph
 *
 * --- Example Template
 * Generated by `./gradlew :query:generateEligibilityRulesGraph`. Do not edit by hand.
 *
 * ## Example
 *
 * flowchart TD
 *   RulesetName1["RulesetName1"]
 *   RulesetName2["RulesetName2"]
 *   notConfirmed["notConfirmed"]
 *   confirmed["confirmed"]
 *
 *   RulesetName1 -->|PASS| RulesetName2
 *   RulesetName1 -->|FAIL| notConfirmed
 *
 *   RulesetName2 -->|PASS| confirmed
 *   RulesetName2 -->|FAIL| notConfirmed
 *
 * ### Nodes
 *
 * **RulesetName1** (RuleSet)
 * - RuleA: Description
 *
 *
 * **RulesetName2** (RuleSet)
 * - RuleB: Description
 *
 *
 * **notConfirmed** (Outcome)
 *
 * **confirmed** (Outcome)
 *
 *
 * ## Rule catalogue
 *
 * | Rule | Description | RuleSets | Trees |
 * | --- | --- | --- | --- |
 * | RuleA | Description | RulesetName1 | Diagram Name |
 * | RuleB | Description | RulesetName2 | Diagram Name |
 * ❯
 * ---
 *
 */
object RulesGraphMarkdownRenderer {

  fun render(graphs: List<RulesGraph>): String = buildString {
    appendLine("# Eligibility rules graph")
    appendLine()
    appendLine("Generated by `./gradlew :query:generateEligibilityRulesGraph`. Do not edit by hand.")
    appendLine()

    graphs.sortedBy { it.treeName }.forEach { graph ->
      appendLine("## ${graph.treeName}")
      appendLine()
      appendLine("```mermaid")
      appendLine("flowchart TD")
      /*
       RulesetName1["RulesetName1"]
       RulesetName2["RulesetName2"]
       notConfirmed["notConfirmed"]
       confirmed["confirmed"]
       */
      graph.nodes.forEach { node ->
        appendLine("  ${node.id}[\"${escape(node.title)}\"]")
      }
      /*
       RulesetName1 -->|PASS| RulesetName2
       RulesetName1 -->|FAIL| notConfirmed
       RulesetName2 -->|PASS| confirmed
       RulesetName2 -->|FAIL| notConfirmed
       */
      graph.edges.forEach { edge ->
        appendLine("  ${edge.from} -->|${edge.label}| ${edge.to}")
      }
      appendLine("```")
      // mermaid drawing closed
      appendLine()

      appendLine("### Nodes")
      appendLine()
      graph.nodes.forEach { node ->
        appendLine(renderNode(node))
        appendLine()
      }
    }

    appendLine("## Rule catalogue")
    appendLine()
    appendLine("| Rule | Description | RuleSets | Trees |")
    appendLine("| --- | --- | --- | --- |")
    catalogueRows(graphs).forEach { row ->
      appendLine("| ${escapeTable(row.className)} | ${escapeTable(row.description)} | ${escapeTable(row.ruleSets)} | ${escapeTable(row.trees)} |")
    }
    appendLine()
  }

  private fun renderNode(node: GraphNode): String = buildString {
    val kind = when (node.kind) {
      GraphNodeKind.RULE_SET -> "RuleSet"
      GraphNodeKind.OUTCOME -> "Outcome"
    }
    append("**${node.title}** ($kind)")
    if (node.kind == GraphNodeKind.RULE_SET) {
      appendLine()
      if (node.rules.isEmpty()) {
        appendLine("- (no rules — always PASS)")
      } else {
        node.rules.forEach { rule ->
          appendLine("- `${rule.className}`: ${rule.description}")
        }
      }
    }
  }

  private fun escape(value: String): String = value.replace("\"", "#quot;")

  private fun escapeTable(value: String): String = value.replace("|", "\\|")

  private fun catalogueRows(graphs: List<RulesGraph>): List<CatalogueRow> {
    data class Key(val className: String, val description: String)
    val byRule = linkedMapOf<Key, MutableList<Pair<String, String>>>()
    graphs.sortedBy { it.treeName }.forEach { graph ->
      graph.nodes.forEach { node ->
        node.rules.forEach { rule ->
          byRule.getOrPut(Key(rule.className, rule.description)) { mutableListOf() }
            .add(graph.treeName to node.title)
        }
      }
    }
    return byRule.map { (key, uses) ->
      CatalogueRow(
        className = key.className,
        description = key.description,
        ruleSets = uses.map { it.second }.distinct().sorted().joinToString(", "),
        trees = uses.map { it.first }.distinct().sorted().joinToString(", "),
      )
    }.sortedBy { it.className }
  }

  private data class CatalogueRow(
    val className: String,
    val description: String,
    val ruleSets: String,
    val trees: String,
  )
}
