package uk.gov.justice.digital.hmpps.singleaccommodationserviceapi.query.eligibility.graph

object RulesGraphTextRenderer {

  fun render(graphs: List<RulesGraph>): String = buildString {
    appendLine("# Eligibility rules graph")
    appendLine()
    appendLine("Generated by `./gradlew :query:generateEligibilityRulesGraph`. Do not edit by hand.")
    appendLine()

    graphs.sortedBy { it.treeName }.forEach { graph ->
      appendLine(graph.treeName)
      graph.nodes.forEach { node ->
        appendLine("  ${node.id}(\"${escape(node.title)}\")")
        appendLine("----")
        appendLine(renderNode(node))
        appendLine()
      }
      appendLine()
    }
  }

  private fun renderNode(node: GraphNode): String = buildString {
    val kind = when (node.kind) {
      GraphNodeKind.RULE_SET -> "RuleSet"
      GraphNodeKind.OUTCOME -> "Outcome"
    }
    append("**${node.title}** ($kind)")
    if (node.kind == GraphNodeKind.RULE_SET) {
      appendLine()
      if (node.rules.isEmpty()) {
        appendLine("- (no rules — always PASS)")
      } else {
        node.rules.forEach { rule ->
          appendLine("- `${rule.className}`: ${rule.description}")
        }
      }
    }
  }

  private fun escape(value: String): String = value.replace("\"", "#quot;")
}
