CREATE TABLE proposed_accommodation(
    id                                  UUID not null,
    crn                                 TEXT not null,
    name                                VARCHAR(200),
    arrangement_type                    VARCHAR(80) not null,
    arrangement_sub_type                VARCHAR(80) not null,
    arrangement_sub_type_description    TEXT,
    settled_type                        VARCHAR(80) not null,
    offender_release_type               VARCHAR(80),
    status                              VARCHAR(80) not null,
    start_date                          DATE,
    end_date                            DATE,
    postcode                            TEXT,
    sub_building_name                   TEXT,
    building_name                       TEXT,
    building_number                     TEXT,
    throughfare_name                    TEXT,
    dependent_locality                  TEXT,
    post_town                           TEXT,
    county                              TEXT,
    country                             TEXT,
    uprn                                TEXT,
    created_at                          TIMESTAMP WITH TIME ZONE default now(),
    last_updated_at                     TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY(id)
);