### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

@bearerToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRwcy1jbGllbnQta2V5In0.eyJzdWIiOiJobXBwcy1hc3Nlc3Mtcmlza3MtYW5kLW5lZWRzLWNsaWVudCIsImdyYW50X3R5cGUiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiYXV0aF9zb3VyY2UiOiJub25lIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwL2F1dGgvaXNzdWVyIiwiZXhwIjoxNzYzNDg5NDg5LCJhdXRob3JpdGllcyI6WyJST0xFX0NSU19QUk9WSURFUiIsIlJPTEVfUFJPQkFUSU9OIiwiUk9MRV9PQVNZU19SRUFEX09OTFkiXSwianRpIjoidXRqdnM4SU4zdktUcExwU3FONFVaR21LS3lvIiwiY2xpZW50X2lkIjoiaG1wcHMtYXNzZXNzLXJpc2tzLWFuZC1uZWVkcy1jbGllbnQifQ.mzYg1nQqMpXVZTdn0vrBt9pHUYm5-73Di8TDgex7P-_8VpSjlt0_QQX-5zshTlu2InffQkxhH-YsBqIxrddBIKWnOyE3camxlgDQ2tkfG_1EPoy6lfjvpLs0gdwX9ClvHiJQM1H7wvs88mW-lgQ3t_ysS0rl499VGwRPtkIRgmmU0unjtQXkDVkmYuoaCV9AnPgH9BQZVuP-id3K9rDeneJhMyLcyiQnynRJfPYm8cN6W1MFrhfYBv7ikBBv87bnG3NHTm0Se-1C55q3HlxV8OxOPnU7dFMlUWUIacvQ1q46Eb6_00TTkBnRteIk6FInpeZcyBeBODNX6aSgiFfuQw

GET http://localhost:8080/aggregator/group/dashboardData?userId=1&postId=1
accept: application/json
Authorization: Bearer {{bearerToken}}

###

