hmpps-auth:
  url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

event:
  details-url:
    proposed-accommodation-updated: http://localhost:8080/proposed-accommodations/#id
    duty-to-refer-updated: http://localhost:8080/duty-to-refers/#id

service:
  commissioned-rehabilitative-services-ui:
    base-url: https://find-and-refer-intervention-dev.hmpps.service.justice.gov.uk

hmpps.sqs:
  enabled: false
  useWebToken: false
  provider: localstack
  topics:
    hmpps-domain-event-topic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-domain-event-topic
  queues:
    sas-domain-events-queue:
      queueName: sas_domain_events_queue
      dlqName: sas_domain_events_dlq
      subscribeTopicId: hmpps-domain-event-topic
      subscribeFilter: '{"eventType":["tier.calculation.changed", "person.community.manager.allocated"]}'
spring:
  config:
    import: classpath:application-infrastructure-local.yml
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO # TRACE - shows what parameters are bound to queries
    org.hibernate.session.metrics: INFO

scheduling:
  enabled: true

sentry:
  sample-rate: 1
  traces-sample-rate: 0.01