package uk.gov.justice.digital.hmpps.singleaccommodationserviceapi.eligibility.domain.enums

enum class ServiceStatus {
  NOT_STARTED, // NO APPLICATION
  NOT_ELIGIBLE, // NO APPLICATION
  UPCOMING, // NO APPLICATION
  AWAITING_ASSESSMENT, // SUITABLE APPLICATION, PLACEMENT NEEDED
  UNALLOCATED_ASSESSMENT, // SUITABLE APPLICATION, PLACEMENT NEEDED
  ASSESSMENT_IN_PROGRESS, // SUITABLE APPLICATION, PLACEMENT NEEDED
  AWAITING_PLACEMENT, // SUITABLE APPLICATION, PLACEMENT NEEDED
  REQUEST_FOR_FURTHER_INFORMATION, // SUITABLE APPLICATION, PLACEMENT NEEDED
  PENDING_PLACEMENT_REQUEST, // SUITABLE APPLICATION, PLACEMENT NEEDED
  ARRIVED, // SUITABLE APPLICATION AND NO ACTION NEEDED
  UPCOMING_PLACEMENT, // SUITABLE APPLICATION AND NO ACTION NEEDED
  DEPARTED, // SUITABLE APPLICATION, PLACEMENT NEEDED
  NOT_ARRIVED, // SUITABLE APPLICATION, PLACEMENT NEEDED
  CANCELLED, // SUITABLE APPLICATION, PLACEMENT NEEDED
}
