---
# Per environment values which override defaults in hmpps-single-accommodation-service-api/values.yaml

generic-service:
  serviceAccountName: hmpps-community-accommodation-api-service-account
  replicaCount: 2

  ingress:
    host: single-accommodation-service-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-single-accommodation-service-api-dev-cert

  env:
    JAVA_OPTS: "-Xmx1000m"
    SPRING_PROFILES_ACTIVE: dev
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SERVICES_AP-DELIUS-CONTEXT-API_BASE-URL: https://approved-premises-and-delius-dev.hmpps.service.justice.gov.uk
    SERVICES_HMPPS-TIER_BASE-URL: https://hmpps-tier-dev.hmpps.service.justice.gov.uk
    SERVICES_PRISONS-API_BASE-URL: https://prison-api-dev.prison.service.justice.gov.uk
    SERVICES_PRISONER-ALERTS-API_BASE-URL: https://alerts-api-dev.hmpps.service.justice.gov.uk
    SERVICES_NOMIS-USER-ROLES-API_BASE-URL: https://nomis-user-roles-api-dev.prison.service.justice.gov.uk
    SERVICES_MANAGE-USERS-API_BASE-URL: https://manage-users-api-dev.hmpps.service.justice.gov.uk
    SERVICES_CASE-NOTES_BASE-URL: https://dev.offender-case-notes.service.justice.gov.uk
    SERVICES_AP-OASYS-CONTEXT-API_BASE-URL: https://approved-premises-and-oasys-dev.hmpps.service.justice.gov.uk
    SERVICES_GOV-UK-BANK-HOLIDAYS-API_BASE-URL: https://www.gov.uk
    SERVICES_MANAGE-POM-CASES_BASE-URL: https://dev.moic.service.justice.gov.uk
    SERVICES_PRISONER-SEARCH_BASE-URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    SERVICES_APPROVED-PREMISES_BASE-URL: https://approved-premises-api-dev.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises

  env_details:
      production_env: false
